### ISSUE TITLE
Step 14 page does not display all the menu items available

### ISSUE THREAD

**Issue by sandra-arato** [node-girls-australia/js-intro-workshop#22]
Page is cut down (see screenshot), maybe `<main  class="page-content">`  should have a min-height: 1080px? not sure whether to fix it a simple way in _layout.scss or on a template level.
<img width="1273" alt="screen shot 2018-03-08 at 19 45 44" src="https://user-images.githubusercontent.com/5035446/37145291-3e2fe07a-230c-11e8-838a-104fd35cd7a9.png">

**Comment by dmison** [comment]
I'm not sure I understand the issue @sandra-arato 

Are you saving that https://node-girls-australia.github.io/js-intro-workshop/step14/ truncated the top of the page?  I can't reproduce that.

What browser/os ?

**Comment by sandra-arato** [comment]
hah sorry not a very good report :) 
any browser, screen has to be equal or smaller than 13". 
Resize the browser (Chrome for me) so that the height of the current view is smaller than 1000px. Then, you cannot scroll to the 'Journey Continues' link on the left nav bar as the footer is positioned fixed to the bottom, and covers the last bit of the menu/nav section.
