### ISSUE TITLE
Step 7 - Comparison Operator >= needs correction

### ISSUE THREAD

**Issue by duyenho** [node-girls-australia/js-intro-workshop#30]
Hi Node Girls,

I would open a PR myself but the code for the tutorial isn't in this repo (?)

Here's the typo:

<img width="1440" alt="greater-than-or-equal-to" src="https://user-images.githubusercontent.com/16188949/43364724-0bb3d26a-9363-11e8-975b-a62d595709bd.png">

**Comment by ButenkoT** [comment]
Thank you @duyenho. The code for this version is on another branch - gh-pages, you are welcome to open pr

**Comment by duyenho** [comment]
Thanks @ButenkoT 

I created a new branch from `gh-pages` and can't seem to push to remote:

```
ERROR: Permission to node-girls-australia/js-intro-workshop.git denied to duyenho.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by duyenho** [comment]
Never mind the above. I forked the repo and opened a PR.

**Comment by ButenkoT** [comment]
https://github.com/node-girls-australia/js-intro-workshop/pull/31
